#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3

#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3



#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3

#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3

#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_tt.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_tt.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_tt.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_tt.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3

#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3

#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3

#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3

#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_comb.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3

#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_tt.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_tt.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT5
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_tt.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso_tt.py --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p-NoChgIsoNoSieiePhoton --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0" & #SPLIT3


#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 --mode all" &
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 --mode all" &
nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --onlyTT --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 --mode all" &
#nohup krenew -t -K 10 -- bash -c "python ratioPlots_chgIso.py --year 2016 --selection dilepOS-nLepVeto2-offZSFll-offZSFllgNoChgIsoNoSieie-NoChgIsoNoSieiePhoton-nJet2p-nBTag1p-mll40  --plot_directory 102X_TTG_ppv16_v7 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 --mode all" &
