python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2p-nBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1-nBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1-nBTag1-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-nBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-nBTag1-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-nBTag2-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3p-nBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3p-nBTag1-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3p-nBTag2-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3p-nBTag3p-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet1-nBTag0                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2-nBTag0                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2-nBTag1                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2-nBTag2                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag0                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag1                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag2                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag3                       --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag0                      --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1                      --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag2                      --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag3                      --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag4p                     --plot_directory 102X_TTG_ppv22_v6 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2p-nBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1-nBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1-nBTag1-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-nBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-nBTag1-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-nBTag2-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3p-nBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3p-nBTag1-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3p-nBTag2-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3p-nBTag3p-offZSFll-mll40        --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet1-nBTag0                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2-nBTag0                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2-nBTag1                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2-nBTag2                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag0                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag1                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag2                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag3                       --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag0                      --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1                      --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag2                      --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag3                      --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag4p                     --plot_directory 102X_TTG_ppv22_v6 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3

