python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample DYJetsToLL_M50_LO #SPLIT19
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample TTLep_pow #SPLIT22
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample TTSemiLep_pow #SPLIT8
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample TTHad_pow #SPLIT20
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample TTLep_NLO #SPLIT43
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample TToLeptons_sch_amcatnlo #SPLIT69
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample WW #SPLIT83
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample ZZ #SPLIT27
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample WWZ #SPLIT14
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample WZZ #SPLIT7
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample ZZZ #SPLIT13
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample TTWZ #SPLIT7
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample TTZZ #SPLIT10
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample GluGluToContinToZZTo2e2mu #SPLIT9
python nanoPostProcessing2018.py --overwrite --skim dilep --year 2018 --processingEra TTGammaEFT_PP_2018_TTG_private_v5 --fileBasedSplitting --sample GluGluToContinToZZTo2e2tau #SPLIT16
