#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 0" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 1" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 2" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 3" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 4" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 5" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 6" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 7" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 8" &
#nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard_modified  --nJobs 10 --job 9" &

nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 0" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 1" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 2" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 3" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 4" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 5" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 6" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 7" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 8" &
nohup krenew -t -K 10 -- bash -c "python genPostProcessing.py --overwrite --processingEra TTGammaEFT_PP_GEN_TTG_v8 --sample ttGamma_NoFullyHad_SM_TTBarrunCard --nJobs 10 --job 9" &
