runNotifier.sh "python fitResults.py --cardfile DY3_DY4p --year 2016 --sorted --postFit --plotImpacts --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY2 --year 2016 --sorted --postFit --plotImpacts --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY3 --year 2016 --sorted --postFit --plotImpacts --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY4 --year 2016 --sorted --postFit --plotImpacts --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY4p --year 2016 --sorted --postFit --plotImpacts --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY5 --year 2016 --sorted --postFit --plotImpacts --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY2_DY3_DY4_DY5 --year 2016 --sorted --postFit --plotImpacts --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY2_DY3_DY4p --year 2016 --sorted --postFit --plotImpacts --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"

runNotifier.sh "python fitResults.py --cardfile DY3_DY4p --year 2016 --sorted --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY2 --year 2016 --sorted --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY3 --year 2016 --sorted --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY4 --year 2016 --sorted --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY4p --year 2016 --sorted --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY5 --year 2016 --sorted --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY2_DY3_DY4_DY5 --year 2016 --sorted --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
runNotifier.sh "python fitResults.py --cardfile DY2_DY3_DY4p --year 2016 --sorted --plotCorrelations --plotCovMatrix --cores 1 --bkgOnly --plotRegionPlot"
